version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  postgres: &postgres
    working_directory: &workdir ~/open # directory where steps will run
    environment: &environment
      DB: postgresql
      DB_HOST: localhost
      DEFAULT_MAX_WAIT_TIME: 10
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_ARTIFACTS: /tmp/test-artifacts
    docker: # run the steps with Docker
      - image: circleci/ruby:2.5-node-browsers # ...with this image as the primary container; this is where all `steps` will run          
      - image: jhawthorn/circleci-postgres-fast
        environment: # environment variables for database
          POSTGRES_USER: root
    parallelism: &parallelism 3
    steps: &steps # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache:
          keys:
            - open-gems-v2-{{ .Branch }}
            - open-gems-v2

      # Install gem dependencies
      - run:
          bundle install --path=vendor/bundle

      - save_cache:
          key: open-gems-v2-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: ./bin/build-ci test

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  mysql: &mysql
    working_directory: *workdir
    environment: &mysql_environment
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
    docker:
      - image: *image
      - image: circleci/mysql:5.7-ram
    parallelism: *parallelism
    steps: *steps

  postgres_rails51:
    <<: *postgres
    environment:
      <<: *environment
      RAILS_VERSION: '~> 5.1.0'

  mysql_rails51:
    <<: *mysql
    environment:
      <<: *mysql_environment
      RAILS_VERSION: '~> 5.1.0'

workflows:
  version: 2
  build:
    jobs:
      - postgres
      - mysql
      - postgres_rails51
      - mysql_rails51
